apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deploy-pro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-deploy-pro
  template:
    metadata:
      labels:
        app: auto-deploy-pro
    spec:
      containers:
      - name: auto-deploy-pro
        image: yourdockerhub/auto-deploy-pro
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
