apiVersion: v1
kind: Service
metadata:
  name: auto-deploy-pro-service
spec:
  selector:
    app: auto-deploy-pro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
